[project]
name = "designsmith"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "its-YogeshChandra", email = "pandittheroyal@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.43.89",
    "fastapi[standard]>=0.141.1",
    "google-genai>=2.23.0",
    "httpx2>=2.12.0",
    "liteparse>=2.14.4",
    "llama-cloud>=2.15.0",
    "llama-index>=0.14.24",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.3",
    "qdrant-client>=1.19.0",
    "requests>=2.34.2",
]

[project.scripts]
designsmith = "designsmith:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
